#include "components.h"

ECS_COMPONENT_DECLARE(Position);
ECS_COMPONENT_DECLARE(BallMovement);
ECS_COMPONENT_DECLARE(PaddleMovement);
ECS_COMPONENT_DECLARE(MovementClamp);
ECS_COMPONENT_DECLARE(RenderableRectangle);
ECS_COMPONENT_DECLARE(PlayerInput);
ECS_COMPONENT_DECLARE(Collider);
ECS_COMPONENT_DECLARE(Score);
ECS_COMPONENT_DECLARE(GameSound);
ECS_COMPONENT_DECLARE(Player);

ECS_TAG_DECLARE(Ball);
ECS_TAG_DECLARE(Paddle);
ECS_TAG_DECLARE(Enemy);
ECS_TAG_DECLARE(Wall);
